dist: trusty
language: node_js
sudo: required
node_js:
  - "14"

env:
  - DOCKER_COMPOSE_VERSION=1.25.0

branches:
  only:
    - master
    - develop

jobs:
  fast_finish: true
  include:
    - stage: test
      script: ./run_tests
    - stage: publish docker image
      script: ./publish_docker_image
    - stage: deploy
      script: ./deploy
