version: "3.7"

services:
  animap_pg_dev:
    container_name: animap_pg_dev
    image: postgres
    environment:
      POSTGRES_DB: animap_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    ports:
      - 5433:5432
    volumes:
      - ./postgres:/data/postgres
    networks:
      - animap
  animap_redis_dev:
    container_name: animap_redis_dev
    image: redis
    command: redis-server
    ports:
      - 6379:6379
    volumes:
      - ./redis:/var/lib/redis
    networks:
      - animap

  animap_pg_test:
    container_name: animap_pg_test
    image: postgres
    environment:
      POSTGRES_DB: animap_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5434:5432
    networks:
      - animap

volumes:
  postgres:
  redis:

networks:
  animap:
    driver: bridge
