version: "3.7"

services:
  postgres:
    container_name: animap_pg
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/data/postgres
    networks:
      - animap

volumes:
  postgres:

networks:
  animap:
    driver: bridge
